/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author JATIN
 */
public class CMPNY_PROFILE extends javax.swing.JFrame {
  java.util.ArrayList<String> a;
    /**
     * Creates new form CMPNY_PROFILE
     */
    public CMPNY_PROFILE() {
        initComponents();
        try{
            
            String q1="",q2="";
               Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_1","root","");
            Statement s=c.createStatement();
        ResultSet r=s.executeQuery("select * from cmpny_profile where Main="+1);
        if(r.next())
        {
            CN.setText(r.getString(1));
            CT.setText(r.getString(2));
            q1=r.getString(3);
            CW.setText(r.getString(4));
            q2=r.getString(5);    
           
        }
        String s2[]=q2.split("::");
          
            CA1.setText(s2[0]);
            CA2.setText(s2[1]);
            CA3.setText(s2[2]); 
            String s1[]=q1.split("::");
             int i=0;
             while(i>=0)
             {
                 if(s1[i]!="")
                 {
                     CP.addItem(s1[i]);
                     i++;
                 }
                 else
                     i=-1;
             }
             
             
        }catch(Exception e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CW = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CA1 = new javax.swing.JTextField();
        CA2 = new javax.swing.JTextField();
        CA3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        CP = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 0, 600, 500));

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 0, 48)); // NOI18N
        jLabel1.setText("COMPANY PROFILE");

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jLabel3.setText("COMPANY NAME");

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jLabel4.setText("COMPANY TAG LINE");

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jLabel5.setText("COMPANY PARTNERS");

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jLabel6.setText("COMPANIES WEBSITE");

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jLabel7.setText("COMPANY ADDRESS");

        jButton5.setText("UPDATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                                .addGap(109, 109, 109)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(CN, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CT, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CW, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(CA3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CA2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CA1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CW, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       try{

            String q2=CN.getText();
            String q3=CT.getText();
            String q4="";
            int t=CP.getItemCount();
                    for (int z=0;z<t;z++)
                        q4+=CP.getItemAt(z)+"::";
             String q5=CW.getText();
             String q6=CA1.getText()+"::"+CA2.getText()+"::"+CA3.getText();                               
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_1","root","");
            PreparedStatement s=c.prepareStatement("update cmpny_profile set  Company_Name=?,Tag_Line=?,Partners=?,Website=?,Address=?  where Main="+1);
            s.setString(1,q2);
            s.setString(2,q3);
            s.setString(3,q4);
            s.setString(4, q5);
            s.setString(5, q6);
            int i=s.executeUpdate();
             if(i>0)
             {javax.swing.JOptionPane.showMessageDialog(this, "DATA INSERTED");
             this.dispose();}
            else
                 javax.swing.JOptionPane.showMessageDialog(this, "DATA NOT INSERTED");
             }catch(Exception e)
        {
            System.out.println(e);
        } 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                String s2=javax.swing.JOptionPane.showInputDialog("Enter the Name of Member");
                CP.addItem(s2);
                  try{

            String q2=CN.getText();
            String q3=CT.getText();
            String q4="";
            int t=CP.getItemCount();
                    for (int z=0;z<t;z++)
                        q4+=CP.getItemAt(z)+"::";
             String q5=CW.getText();
             String q6=CA1.getText()+"::"+CA2.getText()+"::"+CA3.getText();                               
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_1","root","");
            PreparedStatement s=c.prepareStatement("update cmpny_profile set  Company_Name=?,Tag_Line=?,Partners=?,Website=?,Address=?  where Main="+1);
            s.setString(1,q2);
            s.setString(2,q3);
            s.setString(3,q4);
            s.setString(4, q5);
            s.setString(5, q6);
            int i=s.executeUpdate();
             if(i>0)
                javax.swing.JOptionPane.showMessageDialog(this, "DATA INSERTED");
            else
                 javax.swing.JOptionPane.showMessageDialog(this, "DATA NOT INSERTED");
             }catch(Exception e)
        {
            System.out.println(e);
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int g=CP.getSelectedIndex();
        System.out.println(g);    
      
          try{
             CP.removeItemAt(g);
            String q2=CN.getText();
            String q3=CT.getText();
            String q4="";
            int t=CP.getItemCount();
                    for (int z=0;z<t;z++)
                        q4+=CP.getItemAt(z)+"::";
             String q5=CW.getText();
             String q6=CA1.getText()+"::"+CA2.getText()+"::"+CA3.getText();                               
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_1","root","");
            PreparedStatement s=c.prepareStatement("update cmpny_profile set  Company_Name=?,Tag_Line=?,Partners=?,Website=?,Address=?  where Main="+1);
            s.setString(1,q2);
            s.setString(2,q3);
            s.setString(3,q4);
            s.setString(4, q5);
            s.setString(5, q6);
            int i=s.executeUpdate();
             if(i>0)
                javax.swing.JOptionPane.showMessageDialog(this, "DATA INSERTED");
            else
                 javax.swing.JOptionPane.showMessageDialog(this, "DATA NOT INSERTED");
             }catch(Exception e)
        {
            System.out.println(e);
        } 
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CMPNY_PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CMPNY_PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CMPNY_PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CMPNY_PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CMPNY_PROFILE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CA1;
    private javax.swing.JTextField CA2;
    private javax.swing.JTextField CA3;
    private javax.swing.JTextField CN;
    private javax.swing.JComboBox CP;
    private javax.swing.JTextField CT;
    private javax.swing.JTextField CW;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
