/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_1;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author JATIN
 */
public class EMPLOYEE_STARTUP extends javax.swing.JFrame {

    /**
     * Creates new form EMPLOYEE_STARTUP
     */
    public EMPLOYEE_STARTUP() {
        initComponents();
        
    }
    EMPLOYEE_STARTUP(int i){
       initComponents();
       ID.setText(i+"");
        NA.setText("");
P_Track.setText("");
       String s1="",s2="",s3=""; 
       try{       
      Class.forName("com.mysql.jdbc.Driver");
     Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_1","root","");
     Statement s=c.createStatement();    
     ResultSet r1=s.executeQuery("Select Name from employee where E_ID="+i);
     r1.next();
     Name.setText("Welcome, "+r1.getString(1));
           int n=0;
     ResultSet r=s.executeQuery("Select Content from D"+ID.getText().trim()+" where Status='U'");
     while(r.next())
     {        
            n++;
     }
    if(n>0)
    {
        javax.swing.JOptionPane.showMessageDialog(this,"You have "+n+" Unread Messages");
    }
    r=s.executeQuery("Select Project_under from employee_pro where E_ID="+ID.getText().trim());
    if(r.next())
    {
        s1=r.getString(1);       
    }
    r=s.executeQuery("Select * from Screen where Project_Name='"+s1+"'");
    while(r.next())
    {
        s2=r.getString(1);
        s3=r.getString(3);
     P_Track.setText(s2+":"+s3+"\n"+P_Track.getText());      
        P_Track.setEditable(false);
    }
  r=s.executeQuery("select * from Notice");
     while(r.next())
     {
         s1=r.getString(1);
         s2=r.getString(2);
         NA.setText(s1+":-----------\n"+s2+"\n"+NA.getText());
              NA.setEditable(false);
     }
    
  }catch(Exception e)
  {
      System.out.println(e);
  }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        ID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        L5 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        L2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        L3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        NA = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        P_Track = new javax.swing.JTextArea();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        L4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(1366, 760));
        setUndecorated(true);
        getContentPane().setLayout(null);

        Name.setFont(new java.awt.Font("Algerian", 0, 28)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 102, 102));
        Name.setText("WELCOME, MR. JATIN BANGER");
        getContentPane().add(Name);
        Name.setBounds(47, 21, 473, 58);

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1180, 80, 80, 23);

        ID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(ID);
        ID.setBounds(870, 10, 100, 20);

        jLabel2.setText("E_ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(830, 10, 34, 20);

        jSeparator5.setForeground(new java.awt.Color(250, 133, 133));
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(30, 570, 70, 2);

        L5.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        L5.setText("Problem");
        L5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L5MouseExited(evt);
            }
        });
        getContentPane().add(L5);
        L5.setBounds(30, 540, 120, 15);

        L1.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        L1.setText("PROJECT UNDER");
        L1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L1MouseExited(evt);
            }
        });
        getContentPane().add(L1);
        L1.setBounds(30, 300, 139, 26);

        jSeparator1.setForeground(new java.awt.Color(250, 133, 133));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(30, 330, 354, 10);

        L2.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        L2.setText("MY WORK");
        L2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L2MouseExited(evt);
            }
        });
        getContentPane().add(L2);
        L2.setBounds(30, 360, 139, 34);

        jSeparator2.setForeground(new java.awt.Color(250, 133, 133));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(30, 390, 285, 10);

        L3.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        L3.setText("MAILING");
        L3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L3MouseExited(evt);
            }
        });
        getContentPane().add(L3);
        L3.setBounds(30, 420, 122, 34);

        jSeparator3.setForeground(new java.awt.Color(250, 133, 133));
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 450, 217, 10);

        jSeparator6.setForeground(new java.awt.Color(250, 133, 133));
        jSeparator6.setToolTipText("");
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(30, 510, 140, 10);

        jButton1.setText("LOG OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1177, 38, 87, 35);

        NA.setBackground(new java.awt.Color(250, 133, 133));
        NA.setColumns(20);
        NA.setLineWrap(true);
        NA.setRows(5);
        NA.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Voice To ALL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MS Reference Sans Serif", 1, 14))); // NOI18N
        jScrollPane2.setViewportView(NA);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(990, 290, 290, 470);

        P_Track.setBackground(new java.awt.Color(250, 133, 133));
        P_Track.setColumns(20);
        P_Track.setLineWrap(true);
        P_Track.setRows(5);
        P_Track.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PROJECT TRACK", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14))); // NOI18N
        jScrollPane1.setViewportView(P_Track);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(520, 290, 330, 372);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(0, 90, 0, 2);
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(210, 90, 574, 2);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(10, 530, 0, 2);

        L4.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        L4.setText("Request Resource");
        L4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L4MouseExited(evt);
            }
        });
        getContentPane().add(L4);
        L4.setBounds(30, 470, 190, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_1/1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(1366, 760));
        jLabel1.setMinimumSize(new java.awt.Dimension(1366, 760));
        jLabel1.setPreferredSize(new java.awt.Dimension(1366, 760));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1360, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void L1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L1MouseEntered
L1.setForeground(Color.WHITE);              
    }//GEN-LAST:event_L1MouseEntered

    private void L1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L1MouseExited
L1.setForeground(Color.BLACK);        // TODO add your handling code here:
    }//GEN-LAST:event_L1MouseExited

    private void L2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L2MouseEntered
L2.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_L2MouseEntered

    private void L2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L2MouseExited
L2.setForeground(Color.BLACK);        // TODO add your handling code here:
    }//GEN-LAST:event_L2MouseExited

    private void L3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L3MouseEntered
L3.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_L3MouseEntered

    private void L3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L3MouseExited
L3.setForeground(Color.BLACK);        // TODO add your handling code here:
    }//GEN-LAST:event_L3MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
        new START_SCREEN().setVisible(true);
     
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void L4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L4MouseClicked
       new R_RESOURCE().setVisible(true);
    }//GEN-LAST:event_L4MouseClicked

    private void L4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L4MouseEntered
L4.setForeground(Color.WHITE);       
    }//GEN-LAST:event_L4MouseEntered

    private void L4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L4MouseExited
L4.setForeground(Color.BLACK);         
    }//GEN-LAST:event_L4MouseExited

    private void L1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L1MouseClicked
       new Project_under(Integer.parseInt(ID.getText())).setVisible(true);
    }//GEN-LAST:event_L1MouseClicked

    private void L2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L2MouseClicked
new Work(Integer.parseInt(ID.getText())).setVisible(true);      
    }//GEN-LAST:event_L2MouseClicked

    private void L3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L3MouseClicked
          new MY_INBOX(Integer.parseInt(ID.getText())).setVisible(true);
    }//GEN-LAST:event_L3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
NA.setText("");
P_Track.setText("");
       String s1="",s2="",s3=""; 
       try{       
      int n=0;
      Class.forName("com.mysql.jdbc.Driver");
     Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_1","root","");
     Statement s=c.createStatement();    
     ResultSet r=s.executeQuery("Select Content from D"+ID.getText().trim()+" where Status='U'");
     while(r.next())
     {        
            n++;
     }
    if(n>0)
    {
        javax.swing.JOptionPane.showMessageDialog(this,"You have "+n+" Unread Messages");
    }
    r=s.executeQuery("Select Project_under from employee_pro where E_ID="+ID.getText().trim());
    if(r.next())
    {
        s1=r.getString(1);       
    }
    r=s.executeQuery("Select * from Screen where Project_Name='"+s1+"'");
    while(r.next())
    {
        s2=r.getString(1);
        s3=r.getString(3);
     P_Track.setText(s2+":"+s3+"\n"+P_Track.getText());      
        P_Track.setEditable(false);
    }
  r=s.executeQuery("select * from Notice");
     while(r.next())
     {
         s1=r.getString(1);
         s2=r.getString(2);
         NA.setText(s1+":-----------\n"+s2+"\n"+NA.getText());
              NA.setEditable(false);
     }
    
  }catch(Exception e)
  {
      System.out.println(e);
  }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void L5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L5MouseClicked
     new Problem(Integer.parseInt(ID.getText())).setVisible(true);
    }//GEN-LAST:event_L5MouseClicked

    private void L5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L5MouseEntered
       L5.setForeground(Color.WHITE);      // TODO add your handling code here:
    }//GEN-LAST:event_L5MouseEntered

    private void L5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L5MouseExited
        L5.setForeground(Color.BLACK);     // TODO add your handling code here:
    }//GEN-LAST:event_L5MouseExited
           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEE_STARTUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEE_STARTUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEE_STARTUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EMPLOYEE_STARTUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                            System.out.println("jatin thread");
                            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JTextArea NA;
    private javax.swing.JLabel Name;
    private javax.swing.JTextArea P_Track;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
