package project_1;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JATIN
 */
public class LEADER_STARTUP extends javax.swing.JFrame {
String Pr="";
    /**
     * Creates new form LEADER_STARTUP
     */
    public LEADER_STARTUP() {
        initComponents();
    }
LEADER_STARTUP(int i)
{
    initComponents();
    String s1="",s2="";
    ID.setText(i+""); 
    try{       
      int n=0;
      Class.forName("com.mysql.jdbc.Driver");
     Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_1","root","");
     Statement s=c.createStatement();
      ResultSet r1=s.executeQuery("Select Name from employee where E_ID="+i);
     r1.next();
     Name.setText("Welcome, "+r1.getString(1));
     ResultSet r=s.executeQuery("Select * from D"+i+ " where Status='"+"U'");
     while(r.next())
     {        
            n++;
     }
    if(n>0)
    {
        javax.swing.JOptionPane.showMessageDialog(this,"You have "+n+" Unread Messages");
    }
    r=s.executeQuery("select Project_Name from project where Leader="+i);
    if(r.next())
    {
        Pr=r.getString(1);
    }
    r=s.executeQuery("select * from Screen where Project_Name='"+Pr+"'");
    while(r.next())
    {
        s1=r.getString(1);
        s2=r.getString(3);
    P_Track.setText(s1+":"+s2+"\n===================\n"+P_Track.getText());
    P_Track.setEditable(false);
    }
     r=s.executeQuery("select * from Notice");
     while(r.next())
     {
         s1=r.getString(1);
         s2=r.getString(2);
         NA.setText(s1+":-----------\n"+s2+"\n"+NA.getText());
         NA.setEditable(false);
     }
  }catch(Exception e)
  {
      System.out.println(e);
  }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        Name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        NA = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        L1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        L2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        L6 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        P_Track = new javax.swing.JTextArea();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 160, 120));
        setBounds(new java.awt.Rectangle(0, 0, 1366, 768));
        setMaximumSize(new java.awt.Dimension(1366, 760));
        setMinimumSize(new java.awt.Dimension(1366, 760));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 760));
        getContentPane().setLayout(null);

        L8.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        L8.setText("E-NOTICE BOARD");
        L8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L8MouseExited(evt);
            }
        });
        getContentPane().add(L8);
        L8.setBounds(10, 622, 133, 30);

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1170, 70, 90, 23);

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("Release Employees");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 680, 190, 20);

        jSeparator9.setForeground(new java.awt.Color(0, 204, 102));
        jSeparator9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSeparator9);
        jSeparator9.setBounds(10, 663, 65, 10);

        Name.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        Name.setForeground(new java.awt.Color(43, 134, 50));
        Name.setText("WELCOME, MR. JATIN BANGER");
        getContentPane().add(Name);
        Name.setBounds(10, 23, 473, 58);

        jLabel2.setText("E_ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(830, 10, 34, 20);

        ID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(ID);
        ID.setBounds(870, 10, 100, 20);

        NA.setBackground(new java.awt.Color(119, 191, 130));
        NA.setColumns(20);
        NA.setLineWrap(true);
        NA.setRows(5);
        NA.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Voice To ALL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MS Reference Sans Serif", 1, 14))); // NOI18N
        jScrollPane2.setViewportView(NA);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(1030, 250, 250, 470);

        jButton1.setText("LOG OUT");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1160, 30, 110, 35);

        L1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        L1.setText("PROJECT ALLOTED");
        L1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L1MouseExited(evt);
            }
        });
        getContentPane().add(L1);
        L1.setBounds(10, 211, 167, 30);

        jSeparator1.setForeground(P_Track.getBackground());
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 252, 306, 10);

        L2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        L2.setText("SELECT EMPLOYEES");
        L2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L2MouseExited(evt);
            }
        });
        getContentPane().add(L2);
        L2.setBounds(10, 280, 169, 32);

        L3.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        L3.setText("CALL MEETING");
        L3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L3MouseExited(evt);
            }
        });
        getContentPane().add(L3);
        L3.setBounds(10, 346, 124, 29);

        L4.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        L4.setText("Request Resource");
        L4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L4MouseExited(evt);
            }
        });
        getContentPane().add(L4);
        L4.setBounds(10, 420, 176, 34);

        L5.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        L5.setText("MAILING");
        L5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L5MouseExited(evt);
            }
        });
        getContentPane().add(L5);
        L5.setBounds(10, 490, 81, 31);

        L6.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        L6.setText("DAILY WORK");
        L6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L6MouseExited(evt);
            }
        });
        getContentPane().add(L6);
        L6.setBounds(10, 560, 114, 26);

        L7.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        L7.setText("E-NOTICE BOARD");
        L7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L7MouseExited(evt);
            }
        });
        getContentPane().add(L7);
        L7.setBounds(10, 622, 133, 30);

        jSeparator2.setForeground(P_Track.getBackground());
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(10, 318, 260, 10);

        jSeparator3.setForeground(P_Track.getBackground());
        jSeparator3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(10, 386, 222, 10);

        jSeparator4.setForeground(P_Track.getBackground());
        jSeparator4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(10, 459, 176, 5);

        jSeparator5.setForeground(P_Track.getBackground());
        jSeparator5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(10, 532, 138, 10);

        jSeparator6.setForeground(new java.awt.Color(0, 204, 102));
        jSeparator6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(10, 597, 94, 7);

        P_Track.setBackground(new java.awt.Color(119, 191, 130));
        P_Track.setColumns(20);
        P_Track.setLineWrap(true);
        P_Track.setRows(5);
        P_Track.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PROJECT TRACK", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14))); // NOI18N
        jScrollPane1.setViewportView(P_Track);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(530, 280, 293, 372);

        jSeparator7.setForeground(new java.awt.Color(0, 204, 102));
        jSeparator7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(10, 663, 65, 10);

        jSeparator8.setForeground(P_Track.getBackground());
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(10, 90, 696, 12);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_1/8.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1380, 760);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_1/8.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1366, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void L1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L1MouseEntered
       L1.setForeground(Color.GREEN); // TODO add your handling code here:
    }//GEN-LAST:event_L1MouseEntered

    private void L1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L1MouseExited
L1.setForeground(Color.BLACK);        // TODO add your handling code here:
    }//GEN-LAST:event_L1MouseExited

    private void L2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L2MouseEntered
       L2.setForeground(Color.GREEN); // TODO add your handling code here:
    }//GEN-LAST:event_L2MouseEntered

    private void L2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L2MouseExited
  L2.setForeground(Color.BLACK);      // TODO add your handling code here:
    }//GEN-LAST:event_L2MouseExited

    private void L3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L3MouseEntered
       L3.setForeground(Color.GREEN); 
    }//GEN-LAST:event_L3MouseEntered

    private void L3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L3MouseExited
    L3.setForeground(Color.BLACK);   
    }//GEN-LAST:event_L3MouseExited

    private void L4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L4MouseEntered
       L4.setForeground(Color.GREEN); 
    }//GEN-LAST:event_L4MouseEntered

    private void L4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L4MouseExited
    L4.setForeground(Color.BLACK);    // TODO add your handling code here:
    }//GEN-LAST:event_L4MouseExited

    private void L5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L5MouseEntered
       L5.setForeground(Color.GREEN); // TODO add your handling code here:
    }//GEN-LAST:event_L5MouseEntered

    private void L5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L5MouseExited
    L5.setForeground(Color.BLACK);    // TODO add your handling code here:
    }//GEN-LAST:event_L5MouseExited

    private void L6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L6MouseEntered
      L6.setForeground(Color.GREEN);  // TODO add your handling code here:
    }//GEN-LAST:event_L6MouseEntered

    private void L6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L6MouseExited
    L6.setForeground(Color.BLACK);    // TODO add your handling code here:
    }//GEN-LAST:event_L6MouseExited

    private void L7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L7MouseEntered
      L7.setForeground(Color.GREEN);  // TODO add your handling code here:
    }//GEN-LAST:event_L7MouseEntered

    private void L7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L7MouseExited
    L7.setForeground(Color.BLACK);    // TODO add your handling code here:
    }//GEN-LAST:event_L7MouseExited

    private void L2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L2MouseClicked
           String s=javax.swing.JOptionPane.showInputDialog("Enter the Project Name");
      try{
          Class.forName("com.mysql.jdbc.Driver");
           Connection c =DriverManager.getConnection("jdbc:mysql://localhost:3306/project_1","root", "");
           Statement x=c.createStatement();
          ResultSet r=x.executeQuery("select Project_Name from project where Leader="+Integer.parseInt(ID.getText().trim())+" and Status='I'");
          while(r.next())
          {
              if(s.equals(r.getString(1)))
                 new  EMPLOYEE_SELECTIONS(s).setVisible(true);                                 
              else
                  javax.swing.JOptionPane.showMessageDialog(this, "Wrong Name");                
          }           
      }catch(Exception e)
      {
          System.out.println(e);
      }      
        
    }//GEN-LAST:event_L2MouseClicked

    private void L3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L3MouseClicked
                 new CALL_MEETING(Integer.parseInt(ID.getText())).setVisible(true);
                
    }//GEN-LAST:event_L3MouseClicked

    private void L1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L1MouseClicked
       new  P_ALLOTED(Integer.parseInt(ID.getText())).setVisible(true);
    }//GEN-LAST:event_L1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                   START_SCREEN s=new START_SCREEN();
                    s.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void L4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L4MouseClicked
      R_RESOURCE o=new R_RESOURCE();
        o.setVisible(true);
    }//GEN-LAST:event_L4MouseClicked

    private void L5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L5MouseClicked
                   new MY_INBOX(Integer.parseInt(ID.getText())).setVisible(true);
    }//GEN-LAST:event_L5MouseClicked

    private void L6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L6MouseClicked
       String s=javax.swing.JOptionPane.showInputDialog("Enter the Project Name");
      try{
          Class.forName("com.mysql.jdbc.Driver");
           Connection c =DriverManager.getConnection("jdbc:mysql://localhost:3306/project_1","root", "");
           Statement x=c.createStatement();
          ResultSet r=x.executeQuery("select Project_Name from project where Leader="+ID.getText().trim()+" And Status='I'");
          while(r.next())
          {
              if(s.equals(r.getString(1)))
              {
                  javax.swing.JOptionPane.showMessageDialog(this, "WELCOME.!!!!!!");
                  new DAILY_WORK(Integer.parseInt(ID.getText()),s).setVisible(true);
              }
              else
              {
                  javax.swing.JOptionPane.showMessageDialog(this, "Wrong Name");                
              }
          }           
      }catch(Exception e)
      {
          System.out.println(e);
      }     
    }//GEN-LAST:event_L6MouseClicked

    private void L8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L8MouseEntered
       L8.setForeground(Color.GREEN); 
    }//GEN-LAST:event_L8MouseEntered

    private void L8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L8MouseExited
        L8.setForeground(Color.BLACK); 
    }//GEN-LAST:event_L8MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
int q=Integer.parseInt(ID.getText());
        int i=javax.swing.JOptionPane.showConfirmDialog(this,"Kindly,Save the Record of Project as a File \n Press OK to Continue \n Press Cancel To go and Save Data");
if(i==0){
        String s=javax.swing.JOptionPane.showInputDialog("Enter Project Name");
                int s1=0;
                try{
                   Class.forName("com.mysql.jdbc.Driver");
     Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_1","root","");
             Statement x=c.createStatement();
             ResultSet r=x.executeQuery("select Leader from project where Project_name='"+s+"'");
             if(r.next())
                     {
                           s1=r.getInt(1);
                     }
             if(s1==Integer.parseInt(ID.getText()))
             {
                     int j=javax.swing.JOptionPane.showConfirmDialog(this,"Are you sure ..?");
                     System.out.println(j);
                     if(j==0)
                     {
                         int b=x.executeUpdate("Delete  from employee_pro where Project_under='"+s+"'");
                         PreparedStatement z=c.prepareStatement("update employee set Status='A'" );
                         int k=z.executeUpdate();
                         if(b>0)
                         {
                             javax.swing.JOptionPane.showMessageDialog(this,"Employees Released");
                               if(k>0)
                         {
                             javax.swing.JOptionPane.showMessageDialog(this,"Employees State Changed");
                         }
                         }
                         else
                               javax.swing.JOptionPane.showMessageDialog(this,"Sorry,TryAgain");
                       
                     }      
             }else
                   javax.swing.JOptionPane.showMessageDialog(this,"Wrong Access");
             PreparedStatement z=c.prepareStatement("update project set Status='C' where Leader="+q );
             int n=z.executeUpdate();
             if(n>0)
             {
                 javax.swing.JOptionPane.showMessageDialog(this, "Congratulations...!!!!!!!!!!");
             }
              else
                 javax.swing.JOptionPane.showMessageDialog(this,"Try Again");
           }catch(Exception e)
           {
               System.out.println(e);
           }
}

    }//GEN-LAST:event_jLabel4MouseClicked

    private void L8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L8MouseClicked
     java.util.Date d;
        String s="From:"+ID.getText()+" :";
         String v=javax.swing.JOptionPane.showInputDialog("Enter the Notification");   
        d=new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
             String q=sdf.format(d);          
if(!v.equals(""))
{   try{  
        Class.forName("com.mysql.jdbc.Driver");
     Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_1","root","");
     PreparedStatement z=c.prepareStatement("Insert into Notice(Date,Notice) values(?,?)");
     z.setString(1, q);
     z.setString(2,s+v);
     int i=z.executeUpdate();
     if(i>0)
     {
         javax.swing.JOptionPane.showMessageDialog(this, "Notice Published");
     }
      else
         javax.swing.JOptionPane.showMessageDialog(this, "Try again");
    }catch(Exception e)
    {
        System.out.println(e);
    }
}
else
     javax.swing.JOptionPane.showMessageDialog(this, "Enter Something");
    }//GEN-LAST:event_L8MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   NA.setText("");
   P_Track.setText("");
   String s1="",s2="";
   try{       
      int n=0;
      Class.forName("com.mysql.jdbc.Driver");
     Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_1","root","");
     Statement s=c.createStatement();
     ResultSet r=s.executeQuery("Select * from D"+ID.getText().trim()+ " where Status='"+"U'");
     while(r.next())
     {        
            n++;
     }
    if(n>0)
    {
        javax.swing.JOptionPane.showMessageDialog(this,"You have "+n+" Unread Messages");
    }
    r=s.executeQuery("select Project_Name from project where Leader="+ID.getText().trim());
    if(r.next())
    {
        Pr=r.getString(1);
    }
    r=s.executeQuery("select * from Screen where Project_Name='"+Pr+"'");
    while(r.next())
    {
        s1=r.getString(1);
        s2=r.getString(3);
    P_Track.setText(s1+":"+s2+"\n===================\n"+P_Track.getText());
    P_Track.setEditable(false);
    }
     r=s.executeQuery("select * from Notice");
     while(r.next())
     {
         s1=r.getString(1);
         s2=r.getString(2);
         NA.setText(s1+":-----------\n"+s2+"\n"+NA.getText());
         NA.setEditable(false);
     }
  }catch(Exception e)
  {
      System.out.println(e);
  }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line argument
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LEADER_STARTUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LEADER_STARTUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LEADER_STARTUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LEADER_STARTUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LEADER_STARTUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JLabel L8;
    private javax.swing.JTextArea NA;
    private javax.swing.JLabel Name;
    private javax.swing.JTextArea P_Track;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
