/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_1;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author JATIN
 */
public class MD_STARTUP extends javax.swing.JFrame {

    /**
     * Creates new form MD_STARTUP
     */
    public MD_STARTUP() {
        initComponents();
    }
    MD_STARTUP(int i) {
        initComponents();
        ID.setText(i+"");
        String s1="",s2="";
        try{       
      int n=0;
      Class.forName("com.mysql.jdbc.Driver");
     Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_1","root","");
     Statement s=c.createStatement();
      ResultSet r1=s.executeQuery("Select Name from employee where E_ID="+i);
     r1.next();
     Name.setText("Welcome, "+r1.getString(1));
     ResultSet r=s.executeQuery("Select * from D"+i+ " where Status='U'");
     while(r.next())
     {        
            n++;
     }
    if(n>0)
    {
        javax.swing.JOptionPane.showMessageDialog(this,"You have "+n+"Unread Mails");
    }
    r=s.executeQuery("Select * from project");
    while(r.next())
    {
        s1=r.getString(1);
        s2=r.getString(7);
        if(s2.charAt(0)=='C')
                s2="Completed";
        else if(s2.charAt(0)=='I')
                s2="Initiated";
                ORP.setText(s2+":"+s1+"\n================\n"+ORP.getText());
          ORP.setEditable(false);
    }
        r=s.executeQuery("select * from Notice");
     while(r.next())
     {
         s1=r.getString(1);
         s2=r.getString(2);
         NA.setText(s1+":-----------\n"+s2+"\n"+NA.getText());
            NA.setEditable(false);
     }
  }catch(Exception e)
  {
      System.out.println(e);
  }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        L5 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        L7 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        ORP = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        NA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 760));
        setUndecorated(true);
        getContentPane().setLayout(null);

        L1.setBackground(new java.awt.Color(240, 237, 208));
        L1.setFont(new java.awt.Font("Lithos Pro Regular", 0, 12)); // NOI18N
        L1.setText("NEW PROJECT");
        L1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L1MouseExited(evt);
            }
        });
        getContentPane().add(L1);
        L1.setBounds(20, 220, 111, 30);

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1200, 60, 80, 23);

        L5.setFont(new java.awt.Font("Lithos Pro Regular", 0, 12)); // NOI18N
        L5.setText("Employees");
        L5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L5MouseExited(evt);
            }
        });
        getContentPane().add(L5);
        L5.setBounds(20, 610, 110, 30);

        L2.setFont(new java.awt.Font("Lithos Pro Regular", 0, 12)); // NOI18N
        L2.setText("Position");
        L2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L2MouseExited(evt);
            }
        });
        getContentPane().add(L2);
        L2.setBounds(20, 280, 130, 31);

        L3.setFont(new java.awt.Font("Lithos Pro Regular", 0, 12)); // NOI18N
        L3.setText("CALL MEETING");
        L3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L3MouseExited(evt);
            }
        });
        getContentPane().add(L3);
        L3.setBounds(20, 350, 110, 33);

        jLabel2.setText("E_ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(830, 10, 34, 20);

        ID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(ID);
        ID.setBounds(870, 10, 100, 20);

        L4.setFont(new java.awt.Font("Lithos Pro Regular", 0, 12)); // NOI18N
        L4.setText("EDIT COMPANY PROFILE");
        L4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L4MouseExited(evt);
            }
        });
        getContentPane().add(L4);
        L4.setBounds(20, 410, 180, 35);

        L6.setFont(new java.awt.Font("Lithos Pro Regular", 0, 12)); // NOI18N
        L6.setText("E-NOTICE BOARD");
        L6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L6MouseExited(evt);
            }
        });
        getContentPane().add(L6);
        L6.setBounds(20, 540, 120, 41);

        jSeparator1.setForeground(new java.awt.Color(51, 102, 255));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 260, 339, 10);

        jSeparator2.setForeground(new java.awt.Color(51, 102, 255));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(20, 320, 282, 7);

        jSeparator3.setForeground(new java.awt.Color(51, 102, 255));
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(20, 380, 230, 10);

        jSeparator4.setForeground(new java.awt.Color(51, 51, 255));
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(20, 450, 176, 10);

        jSeparator5.setForeground(new java.awt.Color(51, 102, 255));
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(20, 510, 133, 10);

        jSeparator6.setForeground(new java.awt.Color(51, 102, 255));
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(20, 580, 102, 9);

        L7.setFont(new java.awt.Font("Lithos Pro Regular", 0, 12)); // NOI18N
        L7.setText("Mailing");
        L7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                L7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                L7MouseExited(evt);
            }
        });
        getContentPane().add(L7);
        L7.setBounds(20, 480, 90, 14);

        Name.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        Name.setForeground(new java.awt.Color(0, 153, 204));
        Name.setText("WELCOME, MR. JATIN BANGER");
        getContentPane().add(Name);
        Name.setBounds(20, 36, 473, 58);

        jSeparator8.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(157, 100, 718, 10);

        ORP.setBackground(new java.awt.Color(189, 216, 240));
        ORP.setColumns(20);
        ORP.setLineWrap(true);
        ORP.setRows(5);
        ORP.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "ONGOING AND COMPLETED PROJECTS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14))); // NOI18N
        jScrollPane1.setViewportView(ORP);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(500, 220, 380, 400);

        jButton1.setText("LOG OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1190, 20, 90, 35);

        NA.setBackground(ORP.getBackground());
        NA.setColumns(20);
        NA.setLineWrap(true);
        NA.setRows(5);
        NA.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Voice To ALL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MS Reference Sans Serif", 1, 14))); // NOI18N
        jScrollPane2.setViewportView(NA);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(1080, 320, 290, 430);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_1/10.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1380, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void L1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L1MouseEntered
            L1.setForeground(Color.BLUE);
    }//GEN-LAST:event_L1MouseEntered

    private void L1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L1MouseExited
         L1.setForeground(Color.BLACK);
    }//GEN-LAST:event_L1MouseExited

    private void L2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L2MouseEntered
       L2.setForeground(Color.BLUE); // TODO add your handling code here:
    }//GEN-LAST:event_L2MouseEntered

    private void L2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L2MouseExited
L2.setForeground(Color.BLACK);        // TODO add your handling code here:
    }//GEN-LAST:event_L2MouseExited

    private void L3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L3MouseEntered
L3.setForeground(Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_L3MouseEntered

    private void L3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L3MouseExited
L3.setForeground(Color.BLACK);        // TODO add your handling code here:
    }//GEN-LAST:event_L3MouseExited

    private void L4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L4MouseEntered
L4.setForeground(Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_L4MouseEntered

    private void L4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L4MouseExited
L4.setForeground(Color.BLACK);        // TODO add your handling code here:
    }//GEN-LAST:event_L4MouseExited

    private void L6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L6MouseEntered
L6.setForeground(Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_L6MouseEntered

    private void L6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L6MouseExited
L6.setForeground(Color.BLACK);        // TODO add your handling code here:
    }//GEN-LAST:event_L6MouseExited

    private void L1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L1MouseClicked
                    NEW_PROJECT  n=new NEW_PROJECT();
                    n.setVisible(true);
    }//GEN-LAST:event_L1MouseClicked

    private void L2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L2MouseClicked
  new Promote().setVisible(true);
    }//GEN-LAST:event_L2MouseClicked

    private void L3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L3MouseClicked
            new CALL_MEETING(Integer.parseInt(ID.getText())).setVisible(true);
            
    }//GEN-LAST:event_L3MouseClicked

    private void L4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L4MouseClicked
       new  CMPNY_PROFILE().setVisible(true);
    }//GEN-LAST:event_L4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new START_SCREEN().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void L7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L7MouseClicked
        new MY_INBOX(Integer.parseInt(ID.getText())).setVisible(true);
    }//GEN-LAST:event_L7MouseClicked

    private void L7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L7MouseEntered
      L7.setForeground(Color.BLUE); 
    }//GEN-LAST:event_L7MouseEntered

    private void L7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L7MouseExited
      L7.setForeground(Color.BLACK); 
    }//GEN-LAST:event_L7MouseExited

    private void L6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L6MouseClicked
  java.util.Date d;
        String s="From:"+ID.getText()+" :";
         String v=javax.swing.JOptionPane.showInputDialog("Enter the Notification");   
        d=new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
             String q=sdf.format(d);          
if(!v.equals(""))
{   try{  
        Class.forName("com.mysql.jdbc.Driver");
     Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_1","root","");
     PreparedStatement z=c.prepareStatement("Insert into Notice(Date,Notice) values(?,?)");
     z.setString(1, q);
     z.setString(2,s+v);
     int i=z.executeUpdate();
     if(i>0)
     {
         javax.swing.JOptionPane.showMessageDialog(this, "Notice Published");
     }
      else
         javax.swing.JOptionPane.showMessageDialog(this, "Try again");
    }catch(Exception e)
    {
        System.out.println(e);
    }
}
else
     javax.swing.JOptionPane.showMessageDialog(this, "Enter Something");
    }//GEN-LAST:event_L6MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
NA.setText("");
ORP.setText("");
        String s1="",s2="";
        try{       
      int n=0;
      Class.forName("com.mysql.jdbc.Driver");
     Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/project_1","root","");
     Statement s=c.createStatement();
     ResultSet r=s.executeQuery("Select * from D"+ID.getText().trim()+ " where Status='U'");
     while(r.next())
     {        
            n++;
     }
    if(n>0)
    {
        javax.swing.JOptionPane.showMessageDialog(this,"You have "+n+"Unread Mails");
    }
    r=s.executeQuery("Select * from project");
    while(r.next())
    {
        s1=r.getString(1);
        s2=r.getString(7);
          if(s2.charAt(0)=='C')
                s2="Completed";
        else if(s2.charAt(0)=='I')
                s2="Initiated";
        ORP.setText(s2+":"+s1+"\n================\n"+ORP.getText());
          ORP.setEditable(false);
    }
        r=s.executeQuery("select * from Notice");
     while(r.next())
     {
         s1=r.getString(1);
         s2=r.getString(2);
         NA.setText(s1+":-----------\n"+s2+"\n"+NA.getText());
            NA.setEditable(false);
     }
  }catch(Exception e)
  {
      System.out.println(e);
  }        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void L5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L5MouseClicked
      new MD_check().setVisible(true);
    }//GEN-LAST:event_L5MouseClicked

    private void L5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L5MouseEntered
           L5.setForeground(Color.BLUE); // TODO add your handling code here:
    }//GEN-LAST:event_L5MouseEntered

    private void L5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L5MouseExited
           L5.setForeground(Color.BLACK); // TODO add your handling code here:
    }//GEN-LAST:event_L5MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MD_STARTUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MD_STARTUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MD_STARTUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MD_STARTUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MD_STARTUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JTextArea NA;
    private javax.swing.JLabel Name;
    private javax.swing.JTextArea ORP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
